# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
fortran: false

r_github_packages:
    - ropensci/git2r
    - r-lib/usethis
    - r-lib/devtools

r:
    - 3.1
    - 3.2
    - 3.3
    - oldrel
    - release
    - devel

matrix:
  include:
  - r: 3.2
    os: osx
  - r: 3.3
    os: osx
  - r: oldrel
    os: osx
  - r: release
    os: osx


after_success:
  - Rscript -e 'covr::codecov()'
