# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
fortran: false

r:
    - 3.4
    - oldrel
    - release
    - devel

matrix:
  include:
  - r: 3.4
    os: osx
  - r: oldrel
    os: osx
  - r: release
    os: osx


after_success:
  - Rscript -e 'covr::codecov()'
